version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
      - image: appropriate/curl
        command: [curl, --version]

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint source code
          command: npm run lint

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:web \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000

      - run:
          name: Test
          environment:
            AWS_ACCESS_KEY_ID: "0"
            AWS_SECRET_ACCESS_KEY: "0"
            AWS_DEFAULT_REGION: localhost
            DYNAMODB_REGION: localhost
            DYNAMODB_ENDPOINT: http://localhost:8000  # Running inside docker-compose
            GITHUB_ORG: remarkableplace
            GITHUB_CLIENT_ID: client-id
            GITHUB_CLIENT_SECRET: client-secret
            GITHUB_OAUTH_REDIRECT_URI: http://localhost:3001/api/github/authorize/callback
            IS_OFFLINE: "true"
            PAGES_TABLE: pages
            SESSIONS_TABLE: sessions
            SESSION_SECRET: secret
          command: npm test
