version: '3'

services:
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/shell/ || exit 1
      interval: 1s
      timeout: 10s
      retries: 3

  init-dynamodb:
    build:
      context: ../
      dockerfile: .docker/DockerfileDBInit
    volumes:
      - "../:/app/"
    command: /createtable.sh AuthorsDynamoDBTable PagesDynamoDBTable SessionsDynamoDBTable
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=localhost
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
