version: '3'

services:
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000
    restart: always

  init-dynamodb:
    image: garland/aws-cli-docker
    command:
      - /bin/sh
      - -c
      - |
          echo "Initilizing DynamoDB tables"
          aws dynamodb create-table --table-name pages --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=1 --endpoint-url http://dynamodb:8000 || echo "pages table already existed"
          aws dynamodb create-table --table-name sessions --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=1 --endpoint-url http://dynamodb:8000  || echo "sessions table already existed"
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=localhost
    depends_on:
      - dynamodb
