version: '3'

services:
  test-admin:
    container_name: test-admin
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: node /app/src/app-admin
    env_file:
      - ./local.env
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - init-dynamodb
  test-api:
    container_name: test-api
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: node /app/src/app-api
    env_file:
      - ./local.env
    ports:
      - "4001:3000"
    restart: always
    depends_on:
      - init-dynamodb
  test-oauth:
    container_name: test-oauth
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: node /app/src/app-oauth
    env_file:
      - ./local.env
    ports:
      - "4002:3000"
    restart: always
    depends_on:
      - init-dynamodb
  test-web:
    container_name: test-web
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: node /app/src/app-web
    env_file:
      - ./local.env
    ports:
      - "4003:3000"
    restart: always
    depends_on:
      - init-dynamodb
