version: '3'

services:
  dev-admin:
    container_name: dev-admin
    build:
      context: ../
      dockerfile: .docker/DockerfileDev
    volumes:
      - "../src/:/app/src/"
    command: nodemon -w src -e js,pug /app/src/app-admin
    env_file:
      - ./local.env
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - init-dynamodb
  dev-api:
    container_name: dev-api
    build:
      context: ../
      dockerfile: .docker/DockerfileDev
    volumes:
      - "../src/:/app/src/"
    command: nodemon -w src -e js,pug /app/src/app-api
    env_file:
      - ./local.env
    ports:
      - "4001:3000"
    restart: always
    depends_on:
      - init-dynamodb
  dev-oauth:
    container_name: dev-oauth
    build:
      context: ../
      dockerfile: .docker/DockerfileDev
    volumes:
      - "../src/:/app/src/"
    command: nodemon -w src -e js,pug /app/src/app-api
    env_file:
      - ./local.env
    ports:
      - "4002:3000"
    restart: always
    depends_on:
      - init-dynamodb
  dev-web:
    container_name: dev-web
    build:
      context: ../
      dockerfile: .docker/DockerfileDev
    volumes:
      - "../src/:/app/src/"
    command: nodemon -w src -e js,pug /app/src/app-web
    env_file:
      - ./local.env
    ports:
      - "4003:3000"
    restart: always
    depends_on:
      - init-dynamodb
