version: '3'

services:
  test-admin:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: remarkable-place/app
    command: node /app/src/app-admin
    env_file:
      - ./local.env
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - init-dynamodb
  test-api:
    image: remarkable-place/app
    command: node /app/src/app-api
    env_file:
      - ./local.env
    ports:
      - "4001:3000"
    restart: always
    depends_on:
      - test-admin
  test-oauth:
    image: remarkable-place/app
    command: node /app/src/app-oauth
    env_file:
      - ./local.env
    ports:
      - "4002:3000"
    restart: always
    depends_on:
      - test-admin
  test-web:
    image: remarkable-place/app
    command: node /app/src/app-web
    env_file:
      - ./local.env
    ports:
      - "4003:3000"
    restart: always
    depends_on:
      - test-admin
